### ISSUE TITLE
How to search associated models

### ISSUE THREAD

**Issue by admin-it** [elastic/elasticsearch-rails#710] opened 2017-05-01 21:43 UTC
I'm trying to build a search that searches a "Product" table and also its parent "Model" table and the parent table of the "Model" table called the "Brand" table. I've asked the question on stackoverflow and I have done a bit of research but I can't seem to get anywhere and I'm rather confused at this point as to which options I should use for the desired results.  http://stackoverflow.com/questions/43723245/search-associated-models-elastic-search-rails

**Comment by acareaga** [comment] 2017-05-08 17:45
@admin-it have you checked out the `activerecord_associations.rb` example?

https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/examples/activerecord_associations.rb

**Comment by anuj-verma** [comment] 2017-06-01 13:16
Hi @admin-it 

I looked into this issue. The problem is with your as_indexed_json method in Product Model. 
If you want to search for fields of associated models, then you must index their fields in Product Model's elastic-search index.
You can refer below code:
```ruby
def as_indexed_json(options = {})
  as_json(
    only: :name,
    include: {
      normal_model: {
        only: :name,
        include: {
          normal_brand: {
            only: :name
          }    
        }    
      }    
    }    
  )
end
```
As you can see above I have included both `NormalModel` and `NormalBrand` fields in Product Model's Index.

Then in your search method of Product Model, you can specify field names in multi-match query like this:
```ruby
def self.search(query)
  __elasticsearch__.search(
    {    
      query: {
        multi_match: {
          query: query,
          fields: ['name', 'normal_model.name', 'normal_model.normal_brand.name']
        }
      }
    }    
  )
end
```
Elastic-search index will look like this:
```json
{
    "_index": "my_products_index",
    "_type": "product",
    "_id": "1234",
    "_score": 1,
    "_source": {
        "name": "TV",
        "normal_model": {
            "name": "LCD",
            "normal_brand": {
                "name": "Samsung"
            }
        }
    }
}
```
Then you can search in Product Model like this:

1. Search for a product name:
```
> query = Product.search "TV"
> query.results.count
 => 1
> query.results.first._source.as_json
 => {"name"=>"TV", "normal_model"=>{"name"=>"LCD", "normal_brand"=>{"name"=>"Samsung"}}}
```
2. Search for a Normal Model name:
```
> query = Product.search "LCD"
> query.results.count
 => 1
> query.results.first._source.as_json
 => {"name"=>"TV", "normal_model"=>{"name"=>"LCD", "normal_brand"=>{"name"=>"Samsung"}}}
```
3. Search for a Normal Brand name:
```
> query = Product.search "samsung"
> query.results.count
 => 1
> query.results.first._source.as_json
 => {"name"=>"TV", "normal_model"=>{"name"=>"LCD", "normal_brand"=>{"name"=>"Samsung"}}}
```
4. Search for a name which is not present in our Index
```
> query = Product.search "foo"
> query.results.count
 => 0
> query.results.first
 => nil
```

I hope this will help you to solve your problem.

**Comment by admin-it** [comment] 2017-06-01 22:20
Thanks for looking into this! I still can't search the normal_model.name and normal_model.normal_brand.name fields as soon as I override the self.search method. My own implementation doesn't work and neither does the one you provided. When I don't override the search method, then I am able to search the desired columns in the tables, but as soon as I override the search method the only column I can search is the name column in the Product model. I've posted my code below.
`require 'elasticsearch/model'
class Product < ApplicationRecord
	


	include Elasticsearch::Model
	#include Elasticsearch::Model::Callbacks
	

	require 'csv'
	#associations
	belongs_to :category_model
	belongs_to :normal_model
	has_many :order_items
	has_many :quote_items
	has_many :cart_items, dependent: :destroy
	has_many :options, dependent: :destroy
		#validations
		
	validates :pick_three_one, numericality: { greater_than_or_equal_to: 1, allow_blank: true }
	validates :pick_three_two, numericality: { greater_than_or_equal_to: 1, allow_blank: true }
	
	validates :name, presence: true
	validates :part_number, presence: true

	#validates :description, presence: true
	validates :sku, presence: true
	validates :sku, uniqueness: true

	validates :price, presence: true
	validates :price, numericality: { greater_than_or_equal_to: 0.0 }

	validates :weight, presence: true
	validates :weight, numericality: { greater_than_or_equal_to: 0.0 }
	validates :url_key, presence: true
	validates :url_key, uniqueness: true


	

	settings index: { number_of_shards: 1 } do
	  mappings dynamic: 'false' do
	    indexes :name, analyzer: 'english'
	    indexes :description, analyzer: 'english'
	    indexes :part_number, analyzer: 'english'
	    indexes :text, analyzer: 'english'
	    indexes :normal_model, type: 'nested' do
	      indexes :name, analyzer: 'english'
	     
	      indexes :normal_brand, type: 'nested' do
	    	indexes :name, analyzer: 'english'
	      end
	    end
	  end
	end

	
  
	
	
	 def as_indexed_json(options = {})
		  as_json(
		    only: :name,
		    include: {
		      normal_model: {
		        only: :name,
		        include: {
		          normal_brand: {
		            only: :name
		          }    
		        }    
		      }    
		    }    
		  )
	end

	def self.search(query)
	  __elasticsearch__.search(
	    {    
	      query: {
	        multi_match: {
	          query: query,
	          fields: ['name', 'normal_model.name', 'normal_model.normal_brand.name']
	        }
	      }
	    }    
	  )
	end

	
	
	after_commit on: [:update] do
		if self.status == "Viewable On Website & Backend"
    		__elasticsearch__.index_document 
    	else
    		__elasticsearch__.delete_document ignore: 404
    	end
    	
	end
	
	after_commit on: [:create] do
		if self.status == "Viewable On Website & Backend"
    		__elasticsearch__.index_document 
    	end
	end
	
	

 	def get_full_name
 		return self.normal_model.normal_brand.name + " " + self.normal_model.name + " " + self.name	
 	end
 	
 	def self.import_products(file)
 		count = 0
 		products = []
 		previous_records = {
 			  'category' => nil,
	          'category_brand' => nil,
	          'category_model' => nil,
	          'normal_brand' => nil,
	          'normal_model' => nil
	        }
	        
		CSV.foreach(file.path, headers: true, :encoding => 'ISO-8859-1') do |row|
			
			
			
			print count
			count = count + 1
		
			if !previous_records["category"].blank? and previous_records["category"].name == row["category"]
				category = previous_records["category"]
			else
				category = Category.find_by(name: row["category"])
				if category.blank?
					category = Category.create(name: row["category"])
				end	
			end
			
			
			if !previous_records["category_brand"].blank? and previous_records["category_brand"].name == row["brand"]
				category_brand = previous_records["category_brand"]
			else	
				category_brand = category.category_brands.find_by(name: row["brand"])
				if category_brand.blank?
					category_brand = category.category_brands.create(name: row["brand"])	
				end
			end
			
			
			if !previous_records["category_model"].blank? and previous_records["category_model"].name == row["model"]
				category_model = previous_records["category_model"]
			else
				category_model = category_brand.category_models.find_by(name: row["model"])
				if category_model.blank?
					category_model = category_brand.category_models.create(name: row["model"], number: row["model_number"])	
				end
			end
			
			
			if !previous_records["normal_brand"].blank? and previous_records["normal_brand"].name == row["brand"]
				normal_brand = previous_records["normal_brand"]
			else
				normal_brand = NormalBrand.find_by(name: row["brand"])
				if normal_brand.blank?
					normal_brand = NormalBrand.create(name: row["brand"])	
				end
			end
			
			
			if !previous_records["normal_model"].blank? and previous_records["normal_model"].name == row["model"]
				normal_model = previous_records["normal_model"]
			else
				normal_model = normal_brand.normal_models.find_by(name: row["model"])
				if normal_model.blank?
					normal_model = normal_brand.normal_models.create(name: row["model"], number: row["model_number"])
				end
			end
				
				
			part_number = row["part_number"]
			if part_number.blank?
				part_number = "N/A"	
			end
			
			previous_records = {
 			  'category' => category,
	          'category_brand' => category_brand,
	          'category_model' => category_model,
	          'normal_brand' => normal_brand,
	          'normal_model' => normal_model
	        }
			
			
			products << Product.new(normal_model: normal_model, category_model: category_model, name: row["name"], part_number: part_number, url_key: row["url_key"], description: row["description"], sku: row["sku"], price: row["price"], weight: row["weight"], description: row["description"], popularity: row["popularity"])
			
			#Review.create! row.to_hash
		end
		Product.ar_import products
	end
	
    end
    Product.where(status: "Viewable On Website & Backend").includes(normal_model: [:normal_brand]).import force: true`

**Comment by anuj-verma** [comment] 2017-06-02 04:12
Hi @admin-it 
Please provide a sample of your elastic-search index json and the version of elastic-search and elastic-search gems you are using.
I will test this scenario in your version of elastic-search.

**Comment by admin-it** [comment] 2017-06-07 16:20
@anuj-verma Thank you for looking into this. 

When I run bundle install, here are the gems that are installed related to elasticsearch. 

    Using elasticsearch-rails 5.0.0
    Using elasticsearch-api 5.0.4
    Using elasticsearch-transport 5.0.4
    Using elasticsearch 5.0.4
    Using elasticsearch-model 5.0.0

My gemfile: (I am also using Kaminari for pagination)

    #elastic search
    gem 'elasticsearch-model'
    gem 'elasticsearch-rails'

I've attached the code below. My elastic-search index json is as follows (it's included in the Product model file). 

    def as_indexed_json(options={})
	    as_json(
	        include: { 
            	normal_model: { methods: [:name], 
            		include: { 
            			normal_brand: { methods: [:name]}
            		}
            	}
            }
	    )
    end


[Models, Controller, and Gemfile.zip](https://github.com/elastic/elasticsearch-rails/files/1058654/Models.Controller.and.Gemfile.zip)

**Comment by henrikholm89** [comment] 2017-08-02 11:26
@admin-it Have you tried downgrading to 2.0? 

I have had similar issues after I upgraded from 2.0 to 5.0.

**Comment by admin-it** [comment] 2017-08-18 14:27
@henrikholm89 I have not done this yet

**Comment by admin-it** [comment] 2017-08-28 19:37
@karmi  Can you please look into this? I've been able to get things to pretty much work how I need them to with query_string, but with multi_match I cannot get this to work.

**Comment by admin-it** [comment] 2017-08-31 19:08
I've made a little progress but I'm still having issues. Please reference this stackoverflow question.
https://stackoverflow.com/questions/45986946/elasticsearch-cannot-search-nested-field-with-multi-match

**Comment by estolfo** [comment] 2018-08-07 15:08
@admin-it Is this still an issue or can I close it?

**Closed** 2018-08-16 13:01 UTC
