### ISSUE TITLE
Rake task import:all throws LoadError

### ISSUE THREAD

**Issue by datenimperator** [elastic/elasticsearch-rails#638] opened 2016-11-11 15:36 UTC
We've had a file `tag_decorator.rb` under `app/models` which added some methods to another class but did not define a class, let alone one named `TagDecorator`. Running `rake elasticsearch:import:all` led to an error which read:

    LoadError: Unable to autoload constant TagDecorator, expected <path>/app/models/tag_decorator.rb to define it

The issue comes from [lib/elasticsearch/rails/tasks/import.rb#L93](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-rails/lib/elasticsearch/rails/tasks/import.rb#L93) which assumes all file under `app/models` define a class. I'm not sure what would be a clean solution: Maybe the code should not raise a exception if a file name won't map to loadable class name?

**Comment by karmi** [comment] 2016-11-19 17:04
Hi, I think the root of the issue is that you have to load Rails when invoking the task: `rake environment elasticsearch:import:all`. Can you try it like that?

**Comment by estolfo** [comment] 2019-07-18 14:39
Closing as this question is out of date.

**Closed by estolfo** 2019-07-18 14:39 UTC
Labels: question
