### ISSUE TITLE
Infinite loop on SearchRequest.execute!

### ISSUE THREAD

**Issue by kizashi1122** [elastic/elasticsearch-rails#277] opened 2014-10-30 08:06 UTC
I am using elasticsearch-model and added the following code to `application.rb` as described `README.md` to see the detailed information.

```rb
require 'elasticsearch/rails/instrumentation'
```

In this case, It calls `execute!` of `rails / instrumentation / publishers.rb` before calling that of `model / searching.rb`.

When calling `execute!`, `execute_with_instrumentation!` is called. But in this method `execute_without_instrumentation!` which is alias of `execute!` is called (as follows)

https://github.com/elasticsearch/elasticsearch-rails/blob/master/elasticsearch-rails/lib/elasticsearch/rails/instrumentation/publishers.rb#L17-L19

As a result, the following `execute!` is never called. 

https://github.com/elasticsearch/elasticsearch-rails/blob/master/elasticsearch-model/lib/elasticsearch/model/searching.rb#L50-L52

Now I commented out the code `require 'elasticsearch/rails/instrumentation'` to prevent above infinite loop. It works fine.

I if I am wrong please correct me.

**Comment by bcm** [comment] 2015-01-20 01:08
I'm running into exactly the same problem. any chance we can get some forward motion on @ZubKonst's patch?

**Comment by janraasch** [comment] 2015-03-05 08:12
Same problem here. Would love to see a fix for this.

**Comment by bcm** [comment] 2015-04-10 17:30
bump

**Comment by karmi** [comment] 2015-04-11 07:53
@bcm Thanks for the bump, this has slipped me -- asked Konstantin in #278 to sign the CLA so I can merge it.

**Comment by karmi** [comment] 2015-04-11 07:58
@kizashi1122 Apologies for the long delay on this! The weird thing is I cannot reproduce it with the example application, I've added `gem "lograge"` to the Gemfile and neither `require 'elasticsearch/rails/instrumentation'` and `require 'elasticsearch/rails/lograge'` raises an exception.

(The Elasticsearch timing is not displayed when `config.lograge.enabled = true`, however.)

**Comment by ZubKonst** [comment] 2015-04-19 18:14
@karmi It's weird. I can reproduce this issue with the `02-pretty.rb` template. If it helps, I shared `git diff` and `tail dev.log` https://gist.github.com/ZubKonst/0da7749633d04ab282e8

**Closed** 2015-04-24 11:09 UTC
Labels: waiting

**Comment by delwaterman** [comment] 2015-06-25 20:25
I am now getting this error when I require the lograge library:

`require 'elasticsearch/rails/lograge`

Error message: 

```
User Search (530.5ms) {index: "creators-dev", type: "user", body: "{\"query\":{\"filtered\":{\"filter\":{\"bool\":{\"must\":[{\"range\":{\"followers_count\":{\"lte\":28000000}}}]}}}},\"sort\":[{\"_score\":{\"order\":\"desc\"}},{\"followers_count\":{\"order\":\"desc\"}}]}", size: 24, from: 0}
  User Search (530.5ms) {index: "creators-dev", type: "user", body: "{\"query\":{\"filtered\":{\"filter\":{\"bool\":{\"must\":[{\"range\":{\"followers_count\":{\"lte\":28000000}}}]}}}},\"sort\":[{\"_score\":{\"order\":\"desc\"}},{\"followers_count\":{\"order\":\"desc\"}}]}", size: 24, from: 0}
  User Search (530.6ms) {index: "creators-dev", type: "user", body: "{\"query\":{\"filtered\":{\"filter\":{\"bool\":{\"must\":[{\"range\":{\"followers_count\":{\"lte\":28000000}}}]}}}},\"sort\":[{\"_score\":{\"order\":\"desc\"}},{\"followers_count\":{\"order\":\"desc\"}}]}", size: 24, from: 0}
  User Search (530.6ms) {index: "creators-dev", type: "user", body: "{\"query\":{\"filtered\":{\"filter\":{\"bool\":{\"must\":[{\"range\":{\"followers_count\":{\"lte\":28000000}}}]}}}},\"sort\":[{\"_score\":{\"order\":\"desc\"}},{\"followers_count\":{\"order\":\"desc\"}}]}", size: 24, from: 0}
  User Search (530.7ms) {index: "creators-dev", type: "user", body: "{\"query\":{\"filtered\":{\"filter\":{\"bool\":{\"must\":[{\"range\":{\"followers_count\":{\"lte\":28000000}}}]}}}},\"sort\":[{\"_score\":{\"order\":\"desc\"}},{\"followers_count\":{\"order\":\"desc\"}}]}", size: 24, from: 0}
  User Search (530.7ms) {index: "creators-dev", type: "user", body: "{\"query\":{\"filtered\":{\"filter\":{\"bool\":{\"must\":[{\"range\":{\"followers_count\":{\"lte\":28000000}}}]}}}},\"sort\":[{\"_score\":{\"order\":\"desc\"}},{\"followers_count\":{\"order\":\"desc\"}}]}", size: 24, from: 0}
  User Search (530.8ms) {index: "creators-dev", type: "user", body: "{\"query\":{\"filtered\":{\"filter\":{\"bool\":{\"must\":[{\"range\":{\"followers_count\":{\"lte\":28000000}}}]}}}},\"sort\":[{\"_score\":{\"order\":\"desc\"}},{\"followers_count\":{\"order\":\"desc\"}}]}", size: 24, from: 0}
  Rendered search/users/index.json.jbuilder (578.1ms)
Completed 500 Internal Server Error in 1901ms (ActiveRecord: 11.4ms | Elasticsearch: 708034.6ms)
[Rollbar] Reporting exception: stack level too deep
[Rollbar] Exception not reported because Rollbar is disabled

SystemStackError (stack level too deep):
  app/searchers/user/directory/esearch.rb:91:in `count'
  app/views/search/users/index.json.jbuilder:3:in `block in _app_views_search_users_index_json_jbuilder__2582415434253763395_70139413001200'
  app/views/search/users/index.json.jbuilder:2:in `_app_views_search_users_index_json_jbuilder__2582415434253763395_70139413001200'
  app/controllers/search/users_controller.rb:13:in `index'
```

**Comment by delwaterman** [comment] 2015-06-25 20:47
Ah found the issue:

making a separate issue for it: https://github.com/elastic/elasticsearch-rails/issues/435
