### ISSUE TITLE
Impossible to override Repository#search

### ISSUE THREAD

**Issue by lucasmazza** [elastic/elasticsearch-rails#269] opened 2014-10-16 17:58 UTC
After noticing that the `elasticsearch-rails` instrumentation didn't hook in the the Repository class, I though that I could simply override the `search` method in my class and wrap the execution with a `ActiveSupport::Notifications.instrument` block, but it turns out that I can't, due to how the class is designed.

My both attempts of implementing this in the expected child/parent class way have ended up with a `stack level too deep` error:

``` ruby
  def search(query_or_definition, options = {})
    payload = { name: 'Search', klass: klass.to_s, search: query_or_definition }
    ActiveSupport::Notifications.instrument 'search.elasticsearch', payload do
     super
    end
  end

# Or calling the gateway object directly

  def search(query_or_definition, options = {})
    payload = { name: 'Search', klass: klass.to_s, search: query_or_definition }
    ActiveSupport::Notifications.instrument 'search.elasticsearch', payload do
      gateway.search(query_or_definition, options)
    end
  end
```

I'm still trying to track down which piece of code is breaking this - maybe one of the pieces of meta programming of the repository -> gateway relationship is causing it: [this](https://github.com/elasticsearch/elasticsearch-rails/blob/master/elasticsearch-persistence/lib/elasticsearch/persistence/repository.rb#L56-L64) or [this](https://github.com/elasticsearch/elasticsearch-rails/blob/master/elasticsearch-persistence/lib/elasticsearch/persistence/repository.rb#L6-L18). There is any alternative way to achieve this? And I wonder if we really need this kind of code when inheriting from `Repository` since it breaks a lot of the expected behaviour when trying to override any of the instance methods in the gateway class.

**Comment by karmi** [comment] 2015-01-13 10:05
Hey, sorry for missing this, there's a suggestion for implementing notification with Repository in issue #305.

Closing this, if it's OK, let's reopen if you need more advice? Sorry again for the silence on my side.

**Comment by lucasmazza** [comment] 2015-01-13 12:10
@karmi the code on #305 looks reasonable, but it doesn't solve the bigger issue - that we can't properly override the `search` method in the repository class, and that isn't expected behaviour when inheriting from another class.

**Comment by karmi** [comment] 2015-01-13 12:35
@lucasmazza That would indeed be a problem. Can you please provide some executable code which demonstrates it in full, so I don't have to fiddle with it myself and guess it?

**Comment by lucasmazza** [comment] 2015-01-13 12:43
@karmi here is a gist with the piece of code and the output https://gist.github.com/lucasmazza/6ea5dca7d91560ced9aa, hope it helps.

**Comment by karmi** [comment] 2015-01-13 12:52
Thanks!, that's helpful, I'm getting the error, and will look into it.

**Comment by lucasmazza** [comment] 2015-01-13 12:52
Awesome :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart: let me know if you need any help with that

**Comment by karmi** [comment] 2015-01-13 14:54
@lucasmazza So, courtesy of @vhyza, here's code which works:

```ruby
require 'elasticsearch/persistence'

class NotesRepository
  include Elasticsearch::Persistence::Repository

  gateway do

    def search(query_or_definition, options = {})
      puts 'doing a search'
      super
    end

  end
end

puts "Using elasticsearch-persistence #{Elasticsearch::Persistence::VERSION}"
repo = NotesRepository.new
puts repo.search({ query: { match_all: {} } })
```

It makes sense when you think about how the gem is designed and coded, _but_ I totally agree that the code you've posted should work out-of-the-box. The problem is of course the whole delegation from the Repository object to the gateway object, with many levels of flexibility. I'll try to look into solving this, but can't make any promises right now...

**Comment by karmi** [comment] 2015-01-13 15:18
Update: This boils down to the [`method_added`](https://github.com/elasticsearch/elasticsearch-rails/blob/2b74c05304cc22a2e03d6f3657d249d917952db8/elasticsearch-persistence/lib/elasticsearch/persistence/repository.rb#L56-L64) hook which breaks the `super` behaviour.

**Comment by karmi** [comment] 2015-01-14 08:50
@lucasmazza I've spent some time chewing on the problem, and it's ultimately coming from the delegation to the gateway. I'll keep this issue open for reference, but I don't think I'll fix it very soon -- it seems to require some more thought than I have bandwith for at the moment.

**Comment by estolfo** [comment] 2019-07-19 14:00
It's now possible to override the `search` method on a `repository`.

**Closed by estolfo** 2019-07-19 14:00 UTC
Labels: bug
