### ISSUE TITLE
Elasticsearch::Persistence::Repository.search bug

### ISSUE THREAD

**Issue by alolis** [elastic/elasticsearch-rails#334] opened 2015-02-20 02:03 UTC
I believe [Line 49](https://github.com/elasticsearch/elasticsearch-rails/blob/master/elasticsearch-persistence/lib/elasticsearch/persistence/repository/search.rb#L49) should be this

````ruby
response = client.search( { index: index_name, type: type, body: query_or_definition }.merge(options) )
````

instead of 

````ruby
 response = client.search( { index: index_name, type: type, q: query_or_definition }.merge(options) )
````

That `q` key should be `body` instead when a query string is passed to the method as also mentioned in the example [here](https://github.com/elasticsearch/elasticsearch-ruby/blob/master/elasticsearch-api/lib/elasticsearch/api/actions/search.rb#L49)

**Comment by alolis** [comment] 2015-03-10 04:38
Any feedback on this?

**Comment by karmi** [comment] 2015-03-17 18:27
@alolis Sorry for not getting to you sooner, I was too busy with the `elasticsearch-dsl` gem. I am a bit confused by your suggestion -- so what I do is to pass the query as a body when it's a Hash, and as a URL parameter when it's a String, which makese sense, no?

I'll be only partially online in the next two weeks, so please forgive if I'm sketchy with replies.

**Comment by karmi** [comment] 2015-05-12 17:02
@alolis Any news here? I still don't see the issue.

**Comment by alolis** [comment] 2015-05-18 07:59
@karmi , sorry, i never saw your reply! On my initial test, my query was a string and passing it as `q:` was causing a search query exception. I then changed it to `body:` and it worked normally. Maybe I should just make a quick test on the irb to help you reproduce this behavior.

**Comment by karmi** [comment] 2015-05-20 14:40
@alolis I understand your description of the problem, but again: the method [sends Hashes as `body` and Strings as `q`](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-persistence/lib/elasticsearch/persistence/repository/search.rb#L46-L49). In other words, when you pass your search definition as a String, it is intentionally sent as a `q` parameter.

Can you explain a bit better what concrete problem you have with the above in mind?

**Comment by alolis** [comment] 2015-05-20 16:55
If you do the following with the current code, ElasticSearch throws `SearchPhaseExecutionException`

```ruby
qs = '{"query": {"match_all": {}}}'
MyRepositoryClass.search(qs)
```

if you change the line i mentioned in my first post, then it works as expected.

**Comment by karmi** [comment] 2015-05-20 17:03
...but that is expected -- anything sent in as a String is sent as `q` parameter to Elasticsearch, to use the "simple search", with Lucene syntax and what not. In other words, this is by design, and I'd be reluctant to change that, since I believe many people rely on that. If you want to use Query DSL, just send the search definition as a Hash. Is that an option for you? Or is there something which makes it impractical or incovenient for you?

**Comment by alolis** [comment] 2015-05-20 17:26
I am already sending as a Hash and everything works perfectly. I wasn't sure if this is by design or if it was a bug that's why I posted it :) I am sorry if i caused any confusion, it is perfect as it is (covers both simple and more advanced cases)

**Comment by karmi** [comment] 2015-05-20 17:57
Great! It is really by design.

> May I suggest for a comment somewhere (string simple search vs hash query dsl) in order to avoid any future confusion

I tried to make it clear in the documentation here: https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-persistence/lib/elasticsearch/persistence/repository/search.rb#L13-L19, would you have a suggestion for better phrasing?

**Comment by alolis** [comment] 2015-05-20 18:28
Even though I did read it, my brain was absent at that moment I guess. It's probably just fine as it is if nobody else has complained :)

**Comment by karmi** [comment] 2015-05-20 18:38
Great! Let's close this one then! :)

**Closed by karmi** 2015-05-20 18:38 UTC
Labels: waiting
