### ISSUE TITLE
[STORE] caching

### ISSUE THREAD

**Issue by makarchuk** [elastic/elasticsearch-rails#473] opened 2015-09-23 12:52 UTC
Is there ability to cache elastic search results in persistence models? 
It would be a nice to cache some results in e.g. redis and avoid unnecessary http requests

**Comment by estolfo** [comment] 2018-09-21 14:41
I'm going to close this as the issue is quite old. Please open a new issue if you'd like to discuss caching.

**Closed by estolfo** 2018-09-21 14:41 UTC
Labels: waiting-for-user

**Comment by cjreeve** [comment] 2019-11-13 15:48
In Rails, ActiveRecord is used to set instance variables that don't hit the database until they are used. If they are used in a cached page or fragment the query is never made.

I understand that if you use Elasticsearch in the controller the query is made regardless of whether the results are used.

Perhaps Rails.cache.fetch is the standard way of getting around this, but it would be good to know if Elasticsearch already has a better solution.

See the following article for an example of using Rails.cache.fetch
http://dmitrypol.github.io/elastic/redis/2018/01/04/elasticsearch-redis.html
