### ISSUE TITLE
SystemStackError: stack level too deep (new to elasticsearch)

### ISSUE THREAD

**Issue by theresahoeck** [elastic/elasticsearch-rails#792] opened 2018-04-25 14:16 UTC
### hi

We started to integrate Elastic Search to a Portfolio application. 
For our Users and Projects we added ActiveStorrage as a FileUpload. 
When importing Project to elasticsearch it works well, 
but importing User raises an error and also loads ActiveStorrage::Attachment (look at logs). 

<img width="1277" alt="screen shot 2018-04-25 at 16 05 28" src="https://user-images.githubusercontent.com/30858810/39251010-8e8a167e-48a2-11e8-801f-614cd933587a.png">

**User.rb**

```ruby
class User < ApplicationRecord

    extend FriendlyId
    friendly_id :fullname, use: :slugged

    devise :database_authenticatable,
           :recoverable, :rememberable, :trackable

    attr_accessor :remember_me
    
    has_one_attached :avatar

    has_many :projects_roles_users
    has_many :projects, through: :projects_roles_users, dependent: :destroy
    has_many :roles, through: :projects_roles_users, dependent: :destroy

    has_many :subject_users
    has_many :subjects, through: :subject_users, dependent: :destroy

    has_one :agegroups_studycourses_departments_user
    has_one :agegroup, through: :agegroups_studycourses_departments_user, dependent: :destroy
    has_one :department, through: :agegroups_studycourses_departments_user, dependent: :destroy
    has_one :studycourse, through: :agegroups_studycourses_departments_user, dependent: :destroy

    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks


    settings do
      mappings dynamic: false do
        indexes :firstname, type: :text
      end
    end
end
```

**Project.rb**

```ruby
class Project < ApplicationRecord
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks

    before_create :create_as_a_draft

    extend FriendlyId
    friendly_id :title, use: [:slugged, :history]

    has_many :urls, dependent: :destroy
    has_many :assets, dependent: :destroy

    has_many :projects_roles_users, dependent: :destroy
    has_many :users, through: :projects_roles_users
    has_many :roles, through: :projects_roles_users

    has_many :editions_projects, dependent: :destroy
    has_many :editions, through: :editions_projects

    has_many :projects_tags, dependent: :destroy
    has_many :tags, through: :projects_tags

    has_one :slideshow, dependent: :destroy

    has_many_attached :medias, dependent: :destroy
    has_one_attached  :logo, dependent: :destroy

    validates :title, presence: true, uniqueness: true, length: { maximum: 65,
    too_long: "%{count} characters is the maximum allowed" }
    validates :description, presence: true
    validates :en_description, presence: true

    self.per_page = 36

    def create_as_a_draft
        self.draft = true
    end

    settings do
      mappings dynamic: false do
        indexes :title, type: :text, analyzer: :german
        indexes :draft, type: :boolean
      end
    end

    def self.search_published(query)
      self.search({
          query: {
              bool: {
                  must: [
                      {
                          multi_match: {
                              query: query,
                              fields: [:title]
                          }
                      },
                      {
                          match: {
                              draft: false
                          }
                      }]
              }
          }
      })
    end
end
```

**Comment by karmi** [comment] 2018-04-25 15:03
Hi @theresahoeck, I'm afraid I don't have any immediate idea why you're getting the "stack level too deep" error on one model, and not on the other one...

I would suggest to a) remove other integrations from that model, to see if it still happens, and/or b) to remove the `Elasticsearch::Model` specific DSL methods, like `settings`, since they might interfere with another library.

**Comment by theresahoeck** [comment] 2018-04-25 15:39
@karmi Thanks a lot for the fast answer!
I just uncommented: 
has_one_attached :avatar

then it worked 😄

**Comment by karmi** [comment] 2018-04-25 16:50
Hmm, then it somehow clashes with the attachment library, but I don't have any idea why — had a cursory look at the `activestorage` API and it doesn't seem to have an offending method.

For this reason, `elasticsearch-model` supports the [`__elasticsearch__` proxy method](https://github.com/elastic/elasticsearch-rails/tree/master/elasticsearch-model#the-__elasticsearch__-proxy), which you can use instead of calling the `elasticsearch-model` methods directly on the API — if there's a clash, it should solve it, but I'm not sure it's that.

**Comment by theresahoeck** [comment] 2018-04-27 09:57
@karmi , 
I have been using `User.import force: true` for importing the index. 
So I tried `User.__elasticsearch__.import force: true`. 

But there still seems to be an issue with active storage:

<img width="1271" alt="screen shot 2018-04-27 at 11 39 24" src="https://user-images.githubusercontent.com/30858810/39356864-6ccbacc6-4a11-11e8-9c3a-965743bf4df8.png">

Still it was not possible without uncommenting` has_one_attached :avatar`,
what makes me wonder how I will be able to import the indecies while deploying the application.

**Comment by domangi** [comment] 2018-04-27 13:35
Just tried to reproduce the errore (without luck)  by doing the following steps:
1) create a new rails app
2) add active_storage and elasticsearch gems
``` ruby
# Gemfile
...
gem 'activestorage'
gem 'elasticsearch-model', github: 'elastic/elasticsearch-rails', branch: '5.x'
gem 'elasticsearch-rails', github: 'elastic/elasticsearch-rails', branch: '5.x'
```

3) create a model with a single attribute firstname
``` 
$ rails g model User firstname:string
$ rails db:migrate
```
4) install active_storage by adding require "active_storage" to config/application.rb and running
``` 
$ rails activestorage:install
$ rails db:mirgate
```

5) Add modules to User Model
``` ruby
class User < ApplicationRecord
  include Elasticsearch::Model
  has_one_attached :avatar

  settings do
    mappings dynamic: false do
      indexes :firstname, type: :text
    end
  end
end
```

Finally the test from the console

``` ruby
User.import force: true #  => 0
```

@theresahoeck Could you provide more details about the gem versions you are using?

**Comment by theresahoeck** [comment] 2018-05-02 16:17
@domangi thanks for your support. 

You uses branch 5.x version for elasticsearch. I should go for that one as well probably.

This is our Gemfile:

```
`source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.0.beta2'
# Use postgresql as the database for Active Record
gem 'pg', '~> 0.18'
# Use Puma as the app server
gem 'puma', '~> 3.7'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# gem 'compass-rails'
gem 'autoprefixer-rails'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
gem 'font-awesome-sass', '~> 4.7.0'
gem 'chartkick'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
gem 'jquery-rails'
gem 'bootstrap-sass', '~> 3.3.7'


gem 'wdm', '>= 0.1.0' if Gem.win_platform?
gem 'webpacker', '~> 3.2'

# Speed up boot time by caching expensive operations.
gem 'bootsnap', require: false

# elasticsearch
gem 'elasticsearch-model', git: 'git://github.com/elastic/elasticsearch-rails.git', branch: 'master'
gem 'elasticsearch-rails', git: 'git://github.com/elastic/elasticsearch-rails.git', branch: 'master'


gem 'bootstrap-datepicker-rails', '~> 1.6.4'
gem 'will_paginate'
gem 'will_paginate-bootstrap'
gem 'client_side_validations'

gem 'redis', '~> 3.0'
gem 'redis-rails'
gem 'redis-namespace'

# Authentication with devise
gem 'devise'
gem 'net-ldap', '~> 0.15.0'
# Autorisation with CanCanCan. aka user roles
# https://github.com/CanCanCommunity/cancancan
#cancancan - user roles and ability
gem 'cancancan', '~> 2.0'

gem 'friendly_id', '~> 5.1.0'

gem 'rack-attack'

gem 'resque', require: 'resque/server'

gem 'browser'

gem 'chromedriver-helper', '~> 1.0'

# Image uploader - for copying old assets
gem 'mini_magick'
gem 'carrierwave'
gem 'carrierwave-imageoptimizer'
gem 'rmagick', require: false # :require => false um die "already initialized constant ..." warnings nicht zu bekommen

gem 'validate_url'
# OS defpendeny:   apt install imagemagick
gem 'fog'
gem 'unf' # Dependency for fog
gem 'redcarpet'

gem 'aws-sdk', '~> 3'
gem 'aws-sdk-s3', require: false

group :production do
  gem 'rails_12factor'
end

group :development, :test do
  gem 'rubocop', '~>0.49.0', require: false
  gem 'rubocop-checkstyle_formatter', require: false
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'capybara', '~> 2.13'
  gem 'selenium-webdriver'
  gem 'simplecov'
  gem 'simplecov-rcov'
  gem 'brakeman', require: false
  gem 'launchy' # Debugging capybara
  gem 'pry'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'dokku-cli'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'

  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  # gem 'web-console', '>= 3.3.0'
  gem 'better_errors'     # better errors
  gem 'binding_of_caller' # necessary for interactive console on error-pages
  gem 'guard'
  gem 'guard-minitest'
  gem 'ruby-prof'
  gem 'foreman'
  gem 'rails-erd', require: false
end


group :test do
  gem 'minitest'
  gem 'minitest-reporters'
  gem 'minitest-rails-capybara'
  gem 'resque_unit'
  #gem 'database_cleaner'
end


# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

ruby '2.3.3'
`
```

**Comment by domangi** [comment] 2018-05-02 17:09
I tried also with ES 6 and with your elasticsearch gem versions but I was not able to reproduce the error.

**Comment by karmi** [comment] 2018-05-15 07:34
@theresahoeck, hmm hmm, there seems to be some kind of method clash, or some kind of inheritance problem... these are _really_ hard to debug when it's not isolated...

@domangi , many thanks for looking into this!!

**Comment by estolfo** [comment] 2018-07-11 08:53
Hi @theresahoeck Is this still an issue? If so, is there any chance you can provide an isolated example that we can use to try to reproduce it?

**Comment by estolfo** [comment] 2018-07-18 12:38
I'm going to close this, please feel free to open another issue if you have further questions.

**Closed by estolfo** 2018-07-18 12:38 UTC
Labels: waiting-for-user
